AllCops:
  Excludes:
    - config/unicorn.rb
    - db/**
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
  Max: 150

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Lint/ToJSON:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Layout/LineLength:
  Max: 130

Naming/VariableNumber:
  Enabled: false
